---

stages:
  - build
  - test
  - evaluate

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DEFAULT_VCS_CHECKOUT: ""
    - if: $CI_COMMIT_TAG
      variables:
        DEFAULT_VCS_CHECKOUT: ""
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEFAULT_VCS_CHECKOUT: $CI_COMMIT_REF_NAME

include:
  - component: gitlab.com/polymathrobotics/polymath_core/ros2-package@ci-1.3
    inputs:
      base_image: docker.io/polymathrobotics/ros:humble-builder-ubuntu

# Build all packages in the workspace and run their test suites
ros2_build_and_test:
  extends: .ros2_build_and_test
  variables:
    PACKAGES: ""
