---
# Apply Polymath Code Standard formatters and linters
repos:
  - repo: ~/dev/polymath/infra/polymath_code_standard
    rev: feafa20be0c307cccb867209885ce4f83a34e9ce
    hooks:
      # Everything
      - id: polymath-general
      - id: polymath-copyright
        args: [--license, Apache-2.0, --wildcard-copyright-org, --reuse-style]
      # Implementation
      - id: polymath-cmake
      - id: polymath-cpp
        exclude: ^pstop_c/
      - id: polymath-json
      - id: polymath-python
      # Mark(up/down)
      - id: polymath-markdown
      - id: polymath-shell
      - id: polymath-xml
      - id: polymath-yaml
