#!/bin/sh
# SPDX-FileCopyrightText: 2026 Polymath Robotics
# SPDX-License-Identifier: Apache-2.0
# NetworkManager dispatcher: clear stale ARP/neighbor cache when the pstop
# tether comes up, so the host doesn't sit on an INCOMPLETE neighbor from a
# previous boot (one half of the "needs a power cycle" symptom).
# Install: sudo cp to /etc/NetworkManager/dispatcher.d/ ; chmod +x
[ "$1" = "esp-pstop0" ] || exit 0
[ "$2" = "up" ] && ip neigh flush dev esp-pstop0
exit 0
