# SPDX-FileCopyrightText: 2026 Polymath Robotics
# SPDX-License-Identifier: Apache-2.0

# Build-only extension: never edit component-manager-owned sources in place.
# Fail on upstream source drift so upgrades cannot silently change queue semantics.
idf_component_get_property(tusb_dir espressif__tinyusb COMPONENT_DIR)
idf_component_get_property(tusb_lib espressif__tinyusb COMPONENT_LIB)
if(NOT TARGET ${tusb_lib})
    message(FATAL_ERROR "TinyUSB target must exist before applying the defer extension")
endif()
file(SHA256 "${tusb_dir}/CMakeLists.txt" tusb_cmake_sha)
if(NOT tusb_cmake_sha STREQUAL "4198bde29dfe2d6db0564a1527707647a3f79de8036520adfbb5c13f585efd8c")
    message(FATAL_ERROR "TinyUSB build rules changed; audit source properties before applying the defer extension")
endif()
set(usbd_source "${tusb_dir}/src/device/usbd.c")
file(SHA256 "${usbd_source}" usbd_sha)
if(NOT usbd_sha STREQUAL "38de54351d81878e6543f2b022d0c39f45d28c8f0888491796398dec45e727be")
    message(FATAL_ERROR "TinyUSB usbd.c changed; review the nonblocking defer extension before building")
endif()
set(extension "${CMAKE_CURRENT_LIST_DIR}/src/tud_defer_try.inc")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${usbd_source}" "${extension}")
set(patched_source "${CMAKE_CURRENT_BINARY_DIR}/usbd_with_try_defer.c")
configure_file("${CMAKE_CURRENT_LIST_DIR}/src/usbd_with_try_defer.c.in" "${patched_source}" @ONLY)
# Source properties are directory-scoped; preserve them in the original target's
# directory as well as retaining its target-wide private flags/includes.
if(CMAKE_VERSION VERSION_LESS "3.18")
    message(FATAL_ERROR "USB defer extension requires CMake 3.18+ for source-property parity")
endif()
foreach(property COMPILE_FLAGS COMPILE_OPTIONS COMPILE_DEFINITIONS INCLUDE_DIRECTORIES)
    get_source_file_property(value "${usbd_source}" TARGET_DIRECTORY ${tusb_lib} ${property})
    if(NOT value STREQUAL "NOTFOUND")
        set_source_files_properties("${patched_source}" TARGET_DIRECTORY ${tusb_lib} PROPERTIES ${property} "${value}")
    endif()
endforeach()
foreach(property COMPILE_DEFINITIONS_DEBUG COMPILE_DEFINITIONS_RELEASE COMPILE_DEFINITIONS_RELWITHDEBINFO
        COMPILE_DEFINITIONS_MINSIZEREL OBJECT_DEPENDS OBJECT_OUTPUTS SKIP_PRECOMPILE_HEADERS
        SKIP_UNITY_BUILD_INCLUSION UNITY_GROUP)
    get_source_file_property(value "${usbd_source}" TARGET_DIRECTORY ${tusb_lib} ${property})
    if(NOT value STREQUAL "NOTFOUND" AND NOT value STREQUAL "")
        message(FATAL_ERROR "Unhandled TinyUSB source property ${property}; audit the defer extension")
    endif()
endforeach()
get_target_property(tusb_sources ${tusb_lib} SOURCES)
set(replaced 0)
foreach(source IN LISTS tusb_sources)
    if(source MATCHES "(^|/)device/usbd\\.c$")
        list(REMOVE_ITEM tusb_sources "${source}")
        math(EXPR replaced "${replaced} + 1")
    endif()
endforeach()
if(NOT replaced EQUAL 1)
    message(FATAL_ERROR "Expected exactly one TinyUSB device/usbd.c source")
endif()
list(APPEND tusb_sources "${patched_source}")
set_property(TARGET ${tusb_lib} PROPERTY SOURCES "${tusb_sources}")
target_include_directories(${tusb_lib} PRIVATE "${tusb_dir}/src/device" "${CMAKE_CURRENT_LIST_DIR}/include")
