// SPDX-FileCopyrightText: 2026 Polymath Robotics, Inc.
// SPDX-License-Identifier: Apache-2.0

#ifndef PSTOP_CONSTANTS_H
#define PSTOP_CONSTANTS_H

#define PSTOP_SECOND_MS 1000U
#define PSTOP_MINUTE_MS (PSTOP_SECOND_MS * 60U)
#define PSTOP_HOUR_MS (PSTOP_MINUTE_MS * 60U)
#define PSTOP_DAY_MS (PSTOP_HOUR_MS * 24U)

#define PSTOP_MIN_HEARTBEAT 10U
#define PSTOP_MAX_HEARTBEAT (PSTOP_HOUR_MS * 1U)

#endif /* PSTOP_CONSTANTS_H */
