// SPDX-FileCopyrightText: 2026 Polymath Robotics, Inc.
// SPDX-License-Identifier: Apache-2.0

#ifndef PSTOP_ERROR_H
#define PSTOP_ERROR_H

typedef enum {

    PSTOP_OK = 0,
    PSTOP_OPERATOR_NOT_ALLOWED = 1,
    PSTOP_OUT_OF_OPERATOR_SPACE = 2,

    PSTOP_MSG_LOST = 10,
    PSTOP_MSG_REPETITION = 11,
    PSTOP_MSG_DELAYED = 12,
    PSTOP_MSG_OUT_OF_ORDER = 13,
    PSTOP_MSG_INVALID_CHECKSUM = 14,

    PSTOP_HEARTBEAT_INVALID = 20,
    PSTOP_MESSAGE_TYPE_INVALID = 21,
    PSTOP_MISSED_HEARTBEATS = 22,

    PSTOP_FATAL = 255

} pstop_error_t;

#endif /* PSTOP_ERROR_H */
