// SPDX-FileCopyrightText: 2026 Polymath Robotics
// SPDX-License-Identifier: Apache-2.0

/**
 * @file dcs_admin_html.h
 * @brief Static HTML for the / index page. Values come from /state.json,
 * so no per-request templating. Kept verbatim from the pre-refactor main.c.
 */

#pragma once

/* Role branding — the same page serves both device roles. The remote is
 * the default; the machn project overrides both macros from its CMake
 * (target_compile_definitions on dcs_support). Icon = a percent-encoded
 * emoji inside an inline SVG data URI (no external assets; the admin
 * server ships no favicon file). */
#ifndef DCS_PAGE_TITLE
  #define DCS_PAGE_TITLE "PSTOP Remote"
#endif
#ifndef DCS_PAGE_ICON
  #define DCS_PAGE_ICON "%F0%9F%9B%91" /* stop sign, percent-encoded for the data URI */
#endif
#ifndef DCS_PAGE_EMOJI
  #define DCS_PAGE_EMOJI "\xF0\x9F\x9B\x91" /* the same glyph, literal UTF-8, for the heading */
#endif

static const char k_index_html[] =
  "<!DOCTYPE html><html><head>"
  "<meta charset='utf-8'>"
  "<meta name='viewport' content='width=device-width,initial-scale=1'>"
  "<title>" DCS_PAGE_TITLE
  "</title>"
  "<link rel='icon' href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>"
  "<text y='.9em' font-size='90'>" DCS_PAGE_ICON
  "</text></svg>\">"
  /* Palette + component styles adopted from the pstop-fleet console so the
   * two consoles read as one system. Same CSS custom properties/tokens. */
  "<style>*{box-sizing:border-box}"
  ":root{--bg:#0d1117;--panel:#161b22;--panel2:#1b212a;--line:#30363d;"
  "--fg:#e6edf3;--dim:#8b949e;--acc:#58a6ff;--ok:#3fb950;--warn:#d29922;"
  "--err:#f85149;--violet:#bc8cff;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}"
  "html,body{margin:0}"
  "body{background:var(--bg);color:var(--fg);font:14px/1.45 system-ui,-apple-system,'Segoe UI',sans-serif}"
  "main{max-width:940px;margin:0 auto;padding:16px 20px 60px}"
  ".top{position:sticky;top:0;z-index:20;background:var(--panel);border-bottom:1px solid var(--line)}"
  "header{display:flex;align-items:baseline;gap:14px;padding:11px 20px 9px;max-width:940px;margin:0 auto}"
  ".brand{font-weight:700;letter-spacing:.12em;color:var(--acc);font-size:1.02rem;white-space:nowrap}"
  "a{color:var(--acc)}"
  ".hero{background:linear-gradient(180deg,var(--panel2),var(--panel));border:1px solid var(--line);"
  "border-radius:12px;padding:16px 20px;margin-top:16px}"
  ".hlabel{font-size:.7rem;letter-spacing:.14em;text-transform:uppercase;color:var(--dim);font-weight:600}"
  ".hip{display:flex;align-items:center;gap:12px;margin:5px 0 7px;flex-wrap:wrap}"
  "#vpnip{font-size:1.95rem;font-weight:700;color:var(--acc);font-family:var(--mono);"
  "font-variant-numeric:tabular-nums;word-break:break-all}"
  ".hsub{color:var(--dim);font-size:.82rem;display:flex;flex-wrap:wrap;gap:10px;align-items:center}"
  ".hsub .mono{color:var(--fg)}"
  ".panel{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:14px 16px;margin-top:14px}"
  ".secttl{font-size:.8rem;color:var(--dim);letter-spacing:.1em;font-weight:600;text-transform:uppercase;"
  "margin:0 0 10px}"
  ".secttl small{text-transform:none;letter-spacing:0;font-weight:400}"
  ".tblwrap{overflow-x:auto;border:1px solid var(--line);border-radius:8px;background:var(--panel)}"
  "table{border-collapse:collapse;width:100%;font-size:.85rem}"
  "th{color:var(--dim);text-align:left;font-size:.68rem;letter-spacing:.08em;font-weight:600;"
  "padding:8px 12px;border-bottom:1px solid var(--line);white-space:nowrap;background:var(--panel2)}"
  "td{padding:7px 12px;border-bottom:1px solid #21262d;vertical-align:top}"
  "tr:last-child td{border-bottom:none}"
  ".mono{font-family:var(--mono);font-variant-numeric:tabular-nums}"
  ".dim{color:var(--dim)}.small{font-size:.78rem}"
  ".ok{color:var(--ok)}.bad{color:var(--err)}"
  ".chip{display:inline-block;padding:1px 8px;border-radius:10px;font-size:.7rem;font-weight:700;"
  "letter-spacing:.04em;border:1px solid;vertical-align:middle}"
  ".chip.idle{color:var(--ok);border-color:#3fb95055;background:#3fb95014}"
  ".chip.off{color:var(--dim);border-color:var(--line);background:#21262d}"
  ".chip.warn{color:var(--warn);border-color:#d2992255;background:#d2992214}"
  ".chip.blue{color:var(--acc);border-color:#58a6ff55;background:#58a6ff14}"
  ".chip.red{color:#ff7b72;border-color:#f8514966;background:#f8514914}"
  ".btn{background:#21262d;color:var(--fg);border:1px solid var(--line);border-radius:6px;"
  "padding:5px 12px;font:inherit;font-size:.82rem;cursor:pointer}"
  ".btn:hover{border-color:var(--dim)}"
  ".btn.primary{background:#1f6feb;border-color:#1f6feb;font-weight:600}"
  ".btn.primary:hover{background:#388bfd}"
  ".btn.danger{color:#ff7b72;border-color:#f8514955}"
  ".btn.danger:hover{background:#f8514914;border-color:var(--err)}"
  ".btn.icon{padding:3px 9px;font-size:.78rem}"
  "input,select{background:var(--bg);color:var(--fg);border:1px solid var(--line);"
  "border-radius:6px;padding:6px 9px;font:inherit;font-size:.85rem}"
  "input:focus,select:focus{outline:none;border-color:var(--acc)}"
  ".mrow{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0 4px}"
  "canvas{background:#0d1117;border:1px solid #30363d;display:block}"
  ".bd{font-size:.85em;line-height:1.5;min-height:6.4em}"
  ".bd .row{display:flex;justify-content:space-between;gap:8px}"
  ".bd .row.dim{color:#6e7681}"
  ".panel p{color:var(--fg);margin:.55em 0}p small{color:var(--dim)}</style></head><body>"
  /* Sticky top bar (fleet .top / .brand) */
  "<div class='top'><header><span class='brand'>" DCS_PAGE_EMOJI " " DCS_PAGE_TITLE
  "</span><span id='hdrml' class='dim small'>-</span>"
  "<span id='hdrfw' class='dim small' style='margin-left:auto'>-</span></header></div>"
  "<main>"
  /* Hero: the unit's tailnet address, front and centre. */
  "<div class='hero'>"
  "<div class='hlabel'>Tailscale IP</div>"
  "<div class='hip'><span id='vpnip'>-</span>"
  "<button id='vpncopy' class='btn icon' type='button' title='Copy'>copy</button></div>"
  "<div class='hsub'><span class='chip off' id='mlchip'>-</span>"
  "<span>LAN <span id='localip' class='mono'>-</span></span>"
  "<span>public <span id='publicip' class='mono'>-</span></span>"
  "<span>DERP region <span id='derpreg' class='mono'>-</span> "
  "<span id='derplock' class='chip'></span></span></div></div>"
#ifdef DCS_PAGE_MACHINE
  /* Machine-role: operator allowlist is the add/remove-peer equivalent —
   * which remotes may re-arm this machine (empty => every remote stop-only). */
  "<div class='panel'>"
  "<div class='secttl'>Operator allowlist <small>(remotes allowed to re-arm this machine; empty = all "
  "stop-only)</small></div>"
  "<div class='tblwrap'><table><thead><tr><th>Operator ID</th><th></th></tr></thead>"
  "<tbody id='opbody'></tbody></table></div>"
  "<div class='mrow'><input id='opid' placeholder='0x01d7791c or decimal' style='min-width:16em'>"
  "<button id='opadd' class='btn primary' type='button'>Add operator</button>"
  "<span id='opmsg' class='small dim'></span></div></div>"
#else
  /* Remote-role: add/remove the machine peers this remote bonds to. */
  "<div class='panel'>"
  "<div class='secttl'>Machine peers <small>(bond targets, slots 0-3 &mdash; live)</small></div>"
  "<div class='tblwrap'><table>"
  "<thead><tr><th>Slot</th><th>State</th><th>IP</th><th>Port</th><th>ID</th><th></th></tr></thead>"
  "<tbody id='pmbody'></tbody></table></div>"
  "<div class='mrow'>"
  "<select id='pmslot' title='slot'><option value='auto'>auto (next free)</option>"
  "<option value='0'>slot 0</option><option value='1'>slot 1</option>"
  "<option value='2'>slot 2</option><option value='3'>slot 3</option></select>"
  "<input id='pmip' placeholder='192.168.x.x' style='min-width:11em'>"
  "<input id='pmport' type='number' min='1' max='65535' value='8890' style='width:6em' title='port'>"
  "<input id='pmid' placeholder='id 0x.. (optional)' style='width:11em' title='machine id'>"
  "<button id='pmadd' class='btn primary' type='button'>Add machine peer</button>"
  "<span id='pmmsg' class='small dim'></span></div></div>"
#endif
  /* Master LED brightness: one scale over ALL ring output (persisted). */
  "<div class='panel'>"
  "<div class='secttl'>LED brightness <small>(master ring dimming, 10-100% &mdash; live &amp; persisted; floor keeps safety colours visible)</small></div>"
  "<p style='margin:.55em 0'>Brightness: <input id='lbr' type='range' min='10' max='100' value='50'"
  " style='vertical-align:middle'> <span id='lbrv'>-</span>%</p></div>"
  /* All diagnostics/config (unchanged) collected into one fleet-style panel. */
  "<div class='panel'>"
  "<div class='secttl'>Diagnostics</div>"
  "<table>"
  "<tr><th></th><th>Core 0 (D0)</th><th>Core 1 (D1)</th></tr>"
  "<tr><th>ticks</th><td id='t0'>-</td><td id='t1'>-</td></tr>"
  "<tr><th>level</th><td id='l0'>-</td><td id='l1'>-</td></tr>"
  "<tr><th>load</th><td id='load0'>-</td><td id='load1'>-</td></tr>"
  "<tr><th>30s</th>"
  "<td><canvas id='g0' width='180' height='40'></canvas></td>"
  "<td><canvas id='g1' width='180' height='40'></canvas></td></tr>"
  "<tr><th>tasks</th>"
  "<td><div id='tk0' class='bd'>-</div></td>"
  "<td><div id='tk1' class='bd'>-</div></td></tr>"
  "<tr><th>shared</th>"
  "<td colspan='2'><div id='tks' class='bd'>-</div></td></tr>"
  "</table>"
  "<p>tick delta: <span id='delta'>-</span>"
  " &nbsp;|&nbsp; agreement: <span id='agree'>-</span></p>"
  "<p>DERP TX task: <span id='dst'>-</span>"
  " &nbsp;<button class='btn' id='dbtn' type='button'>toggle</button></p>"
  /* Runtime WG suspend toggle removed with POST /api/wg (410 — see
   * api_wg_toggle in dcs_admin_pages.c): a bare vTaskSuspend could park
   * ml_wg_mgr holding the lwIP core lock. Status stays (boot-path pause). */
  "<p>WG manager (DISCO probes): <span id='wgst'>-</span></p>"
  "<p>USB tether: <span id='usbst'>-</span>"
  " &nbsp;<button class='btn' id='usbbtn' type='button'>toggle (reboots)</button></p>"
  "<p style='margin-top:1em'><b>Network interfaces</b> &nbsp; active: <span id='actif' class='ok'>-</span></p>"
  "<p>Ethernet (W5500): <span id='ethst'>-</span>"
  " &nbsp;<button class='btn' id='ethbtn' type='button'>toggle</button></p>"
  "<p>WiFi STA: <span id='wifist'>-</span>"
  " &nbsp;<button class='btn' id='wifibtn' type='button'>toggle</button></p>"
  "<p>USB Ethernet (NCM): <span id='ncmst'>-</span>"
  " &nbsp;<button class='btn' id='ncmbtn' type='button'>toggle (USB re-enum)</button></p>"
  "<p>USB unit (PSTOPxx): <input id='psn' type='number' min='0' max='99' style='width:4em'>"
  " <button class='btn' id='psnbtn' type='button'>set</button> cfg=<span id='psncur'>-</span>"
  " &nbsp;<small>(0=auto from chip ID; reboot to apply)</small></p>"
  "<p>DERP yield: <input id='dms' type='range' min='1' max='100' value='1'"
  " style='vertical-align:middle'> <span id='dmsv'>-</span> ms</p>"
  "<p>WiFi TX power: <input id='txq' type='range' min='8' max='84' value='52'"
  " style='vertical-align:middle'> <span id='txqv'>-</span>"
  " &nbsp;(<span id='txdbm'>-</span> dBm)</p>"
  "<p>RSSI: <span id='rssi'>-</span> dBm"
  " &nbsp;|&nbsp; free heap: <span id='heap'>-</span> KiB"
  " &nbsp;|&nbsp; largest: <span id='lh'>-</span> KiB"
  " &nbsp;|&nbsp; min internal: <span id='hmi'>-</span> KiB"
  " &nbsp;|&nbsp; wg pbuf fails: <span id='pbf'>-</span></p>"
  "<p>SAFETY: boot # <span id='bc'>-</span> &nbsp;|&nbsp;"
  " reset reason: <span id='rr'>-</span> &nbsp;|&nbsp;"
  " valid-mark: <span id='vm'>-</span></p>"
#ifdef DCS_PAGE_MACHINE
  "<p style='margin-top:1em'><b>Stop-circuit relays</b> <small>(series chain: either opens = STOP)</small></p>"
  "<div id='relays' class='bd'>-</div>"
  "<p id='rstop' class='bad' style='display:none;font-weight:bold'>&#9888; RELAY FAULT &mdash; robot stop forced "
  "until feedback recovers</p>"
#else
  "<p style='margin-top:1em'><b>STOP button</b> <small>(dual-channel DPST, live &mdash; no peer needed)</small></p>"
  "<div id='btnstat' style='font-size:1.4em;font-weight:bold;margin:6px 0'>-</div>"
  "<div id='btn' class='bd'>-</div>"
#endif
  "<p style='margin-top:1em'><b>PSTOP peers</b> <small>(bonded devices, live)</small></p>"
  "<div id='peers' class='bd'>-</div>"
  "<p><a href='/admin/'>Admin Panel</a></p>"
  "</div>"
  "</main>"
  "<script>"
  "const N=30;"
  "const h0=new Array(N).fill(0),h1=new Array(N).fill(0);"
  "const c0=document.getElementById('g0'),c1=document.getElementById('g1');"
  "let lastLoad0=0,lastLoad1=0;"
  /* Admin-auth helper: /api routes that mutate config answer 401 until Basic
   * auth is supplied. Prompt once, cache the header, retry. Same-origin, so a
   * browser that already authed /admin/ usually never hits the prompt. */
  "let authHdr=null;"
  "async function authFetch(url,opts){"
  "opts=opts||{};"
  "if(authHdr){opts.headers=Object.assign({},opts.headers,{Authorization:authHdr});}"
  "let r=await fetch(url,opts);"
  "if(r.status===401){"
  "const u=prompt('Admin user:','admin');if(u===null)return r;"
  "const p=prompt('Admin password:');if(p===null)return r;"
  "authHdr='Basic '+btoa(u+':'+p);"
  "opts.headers=Object.assign({},opts.headers,{Authorization:authHdr});"
  "r=await fetch(url,opts);}"
  "return r;}"
  "function draw(c,h,col){"
  "const x=c.getContext('2d'),W=c.width,H=c.height;"
  "x.fillStyle='#0d1117';x.fillRect(0,0,W,H);"
  "x.strokeStyle='#21262d';x.lineWidth=1;"
  "for(const p of[25,50,75]){"
  "const y=Math.round(H-(p/100)*H)+0.5;"
  "x.beginPath();x.moveTo(0,y);x.lineTo(W,y);x.stroke();}"
  "x.strokeStyle=col;x.lineWidth=1.5;x.beginPath();"
  "for(let i=0;i<N;i++){"
  "const px=(i/(N-1))*W,py=H-(h[i]/100)*H;"
  "if(i===0)x.moveTo(px,py);else x.lineTo(px,py);}"
  "x.stroke();}"
  "function renderBd(el,arr,other){"
  "if(!arr){el.textContent='-';return;}"
  "let html='';"
  "for(const[n,p]of arr){"
  "html+='<div class=\"row\"><span>'+n+'</span><span>'+p+'%</span></div>';}"
  "if(other>0){"
  "html+='<div class=\"row dim\"><span>(other)</span><span>'+other+'%</span></div>';}"
  "el.innerHTML=html||'-';}"
#ifdef DCS_PAGE_MACHINE
  "function relayRow(name,cmd,obs,fault,mon){"
  "const match=(fault||0)===0;"
  "const cls=mon?(match?(cmd?'ok':''):'bad'):(cmd?'ok':'');"
  "let st=mon?(match?(cmd?'RUN':'open'):('FAULT ×'+fault)):(cmd?'RUN':'open');"
  "const fb=mon?(obs?'live':'dead'):'not monitored';"
  "return '<div class=\"row\"><span>relay '+name+' &nbsp; coil: '+(cmd?'energized':'released')"
  "+' &nbsp;&middot;&nbsp; feedback: '+fb+'</span>'"
  "+'<span class=\"'+cls+'\">'+st+'</span></div>';}"
  "function renderRelays(j){"
  "const el=document.getElementById('relays');if(!el)return;"
  "const mon=j.relay_feedback_monitored?1:0;"
  "el.innerHTML=relayRow('A',j.e_hi0,j.e_lo0,j.relay_fault_a,mon)+relayRow('B',j.e_hi1,j.e_lo1,j.relay_fault_b,mon);"
  "document.getElementById('rstop').style.display=j.relay_stop?'block':'none';}"
  /* Operator allowlist add/remove (machine's peer-authority surface). */
  "function opMsg(t,err){const e=document.getElementById('opmsg');if(!e)return;"
  "e.textContent=t;e.className='small '+(err?'bad':'ok');}"
  "function renderOps(j){"
  "const tb=document.getElementById('opbody');if(!tb)return;"
  "const ops=j.operators||[];let h='';"
  "if(!ops.length){h='<tr><td class=\"dim\" colspan=\"2\">none &mdash; every remote is stop-only</td></tr>';}"
  "for(const id of ops){h+='<tr><td class=\"mono\">0x'+(id>>>0).toString(16)"
  "+' <span class=\"dim\">('+(id>>>0)+')</span></td>"
  "<td><button class=\"btn danger\" data-op=\"'+id+'\">Remove</button></td></tr>';}"
  "tb.innerHTML=h;"
  "tb.querySelectorAll('button[data-op]').forEach(b=>b.onclick=()=>opDel(b.dataset.op));}"
  "async function opDone(r,m){if(r.status===401){opMsg('Admin auth required',true);return;}"
  "let ok=false;try{ok=(await r.json()).ok;}catch(e){}opMsg(ok?m:'Request failed ('+r.status+')',!ok);poll();}"
  "async function opDel(id){const r=await authFetch('/api/operators?del='+encodeURIComponent(id),{method:'POST'});"
  "opDone(r,'Removed operator');}"
  "async function opAdd(){const v=document.getElementById('opid').value.trim();"
  "if(!v){opMsg('Enter an operator id',true);return;}"
  "const r=await authFetch('/api/operators?add='+encodeURIComponent(v),{method:'POST'});"
  "opDone(r,'Added operator '+v);}"
#else
  "function btnRow(name,hi,lo){"
  "let st,cls;"
  "if(!lo){st='WIRING FAULT';cls='bad';}"
  "else if(hi){st='closed';cls='ok';}"
  "else{st='OPEN (pressed)';cls='';}"
  "return '<div class=\"row\"><span>channel '+name+' &nbsp; drive-hi: '+(hi?'ok':'low')"
  "+' &middot; drive-lo: '+(lo?'ok':'HIGH')+'</span><span class=\"'+cls+'\">'+st+'</span></div>';}"
  "function renderBtn(j){"
  "const el=document.getElementById('btn');if(!el)return;"
  "el.innerHTML=btnRow('A',j.e_hi0,j.e_lo0)+btnRow('B',j.e_hi1,j.e_lo1);"
  "const pressed=(!j.e_hi0)&&(!j.e_hi1),wok=j.e_lo0&&j.e_lo1;"
  "const s=document.getElementById('btnstat');"
  "if(!wok){s.textContent='⚠ WIRING FAULT';s.className='bad';}"
  "else if(pressed){s.textContent='● PRESSED (STOP)';s.className='bad';}"
  "else{s.textContent='○ RELEASED (run)';s.className='ok';}}"
  /* Machine-peer (bond target) add/remove — remote-only. */
  "let pmMachines=[];"
  "function pmMsg(t,err){const e=document.getElementById('pmmsg');if(!e)return;"
  "e.textContent=t;e.className='small '+(err?'bad':'ok');}"
  "function pmChip(s,live){"
  "const cls=s==2?(live?'idle':'warn'):(s==1?'blue':'off');"
  "return '<span class=\"chip '+cls+'\">'+(MS[s]||s)+'</span>';}"
  "function renderPeerMgmt(j){"
  "const tb=document.getElementById('pmbody');if(!tb)return;"
  "pmMachines=j.pstop_machines||[];let h='';"
  "for(let i=0;i<pmMachines.length;i++){const m=pmMachines[i];"
  "if(m.cfg){"
  "const age=j.uptime_ms&&m.last_reply_ms?Math.max(0,j.uptime_ms-m.last_reply_ms):null;"
  "const live=m.state==2&&age!=null&&age<3000;"
  "h+='<tr><td class=\"mono\">'+i+'</td><td>'+pmChip(m.state,live)+'</td>"
  "<td class=\"mono\">'+ip4(m.ip)+'</td><td class=\"mono\">'+m.port+'</td>"
  "<td class=\"mono dim\">0x'+(m.id>>>0).toString(16)+'</td>"
  "<td><button class=\"btn danger\" data-slot=\"'+i+'\">Remove</button></td></tr>';}"
  "else{h+='<tr><td class=\"mono\">'+i+'</td><td><span class=\"chip off\">empty</span></td>"
  "<td class=\"dim\" colspan=\"3\">&mdash;</td><td></td></tr>';}}"
  "tb.innerHTML=h;"
  "tb.querySelectorAll('button[data-slot]').forEach(b=>b.onclick=()=>pmRemove(+b.dataset.slot));}"
  "async function pmDone(r,m){if(r.status===401){pmMsg('Admin auth required',true);return;}"
  "let ok=false;try{ok=(await r.json()).ok;}catch(e){}pmMsg(ok?m:'Request failed ('+r.status+')',!ok);poll();}"
  "async function pmRemove(slot){"
  "const r=await authFetch('/api/pstop_peers?slot='+slot+'&clear=1',{method:'POST'});"
  "pmDone(r,'Removed slot '+slot);}"
  "async function pmAdd(){"
  "let slot=document.getElementById('pmslot').value;"
  "if(slot==='auto'){slot=-1;"
  "for(let i=0;i<pmMachines.length;i++){if(!pmMachines[i].cfg){slot=i;break;}}"
  "if(slot<0){pmMsg('All slots full — remove one first',true);return;}}"
  "const ip=document.getElementById('pmip').value.trim();"
  "const port=document.getElementById('pmport').value||8890;"
  "const id=document.getElementById('pmid').value.trim();"
  "if(!/^\\d{1,3}(\\.\\d{1,3}){3}$/.test(ip)){pmMsg('Enter a valid IPv4 address',true);return;}"
  "let url='/api/pstop_peers?slot='+slot+'&ip='+encodeURIComponent(ip)+'&port='+encodeURIComponent(port);"
  "if(id)url+='&id='+encodeURIComponent(id);"
  "const r=await authFetch(url,{method:'POST'});"
  "pmDone(r,'Added '+ip+':'+port+' (slot '+slot+')');}"
#endif
  "const MS=['idle','bonding','bonded'];"
  "const RS=['initing','bonded','OK','STOP'];"
  "const MLN={0:'idle',1:'wifi-wait',2:'connecting',3:'registering',4:'connected',5:'reconnecting',6:'error'};"
  /* vpn_ip/public_ip come from microlink in MSB-first order (matches
   * microlink_ip_to_str). local_ip is a netif addr in network byte order
   * (LSB-first, per IP2STR) so it needs the reversed decode. */
  "function ip4(v){return[(v>>>24)&255,(v>>>16)&255,(v>>>8)&255,v&255].join('.');}"
  "function ip4n(v){return[v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255].join('.');}"
  "function lnk(ip){return '<a href=\"http://'+ip+'/\" target=\"_blank\" rel=\"noopener\">'+ip+'</a>';}"
  "function pathrtt(o){if(!o.wg_rtt_ms||o.wg_rtt_age_ms>60000)return'';"
  "return ' · path '+o.wg_rtt_ms+' ms '+(o.wg_direct?'(direct)':'(relay)');}"
  "function renderPeers(j){"
  "const el=document.getElementById('peers');if(!el)return;"
  "let h='';"
#ifdef DCS_PAGE_MACHINE
  "for(const m of []){"
#else
  "for(const m of(j.pstop_machines||[])){"
#endif
  "if(!m.cfg)continue;"
  "const age=j.uptime_ms&&m.last_reply_ms?Math.max(0,j.uptime_ms-m.last_reply_ms):null;"
  "const live=m.state==2&&age!=null&&age<3000;"
  "h+='<div class=\"row'+(live?'':' dim')+'\"><span>machine 0x'+(m.id>>>0).toString(16)+' @ "
  "'+lnk(ip4(m.ip))+':'+m.port+' "
  "['+(MS[m.state]||m.state)+']</span>'"
  "+'<span>loop '+m.rtt_ms+' ms'+pathrtt(m)+(age!=null?' · heard '+(age/1000).toFixed(1)+'s "
  "ago':'')+'</span></div>';}"
  "for(const q of(j.bonded_remotes||[])){"
  "const live=q.age_ms<3000;"
  "h+='<div class=\"row'+(live?'':' dim')+'\"><span>remote 0x'+(q.id>>>0).toString(16)+' @ '+lnk(ip4(q.ip))+' "
  "['+(RS[q.state]||q.state)+']</span>'"
  "+'<span>loop≤ '+q.rtt_ms+' ms'+pathrtt(q)+' · heard '+(q.age_ms/1000).toFixed(1)+'s ago</span></div>';}"
  "el.innerHTML=h||'<div class=\"row dim\"><span>none</span><span></span></div>';}"
  /* Known DERP metros we actually home on; number-only for the rest. The two
     we've hit in the field are sfo(2) and dfw(9) — dfw is the region-9 misroute. */
  "function drName(n){var M={2:' sfo',9:' dfw'};return M[n]||'';}"
  "function renderHero(j){"
  "const vi=document.getElementById('vpnip');"
  "vi.textContent=j.vpn_ip?ip4(j.vpn_ip):'not connected';"
  "document.getElementById('localip').textContent=j.local_ip?ip4n(j.local_ip):'-';"
  "document.getElementById('publicip').textContent=j.public_ip?ip4(j.public_ip):'-';"
  "var dr=j.derp_region||0;"
  "document.getElementById('derpreg').textContent=dr?('#'+dr+drName(dr)):'-';"
  /* Region-ownership badge (Q2, region auto-negotiation): LOCKED N (operator
     lock, amber) vs AUTO->N (fleet)/(primary) (auto-applied by the negotiator,
     blue — visibly distinct from both plain AUTO and LOCKED) vs plain AUTO
     (green: server default, no auto-selection applied). */
  "var lk=j.derp_region_locked||0;"
  "var src=j.derp_region_source||'auto';"
  "var aa=j.derp_region_auto_applied||0;"
  "var dl=document.getElementById('derplock');"
  "if(lk){dl.textContent='LOCKED '+lk;dl.className='chip warn';}"
  "else if(src=='auto-fleet'&&aa){dl.textContent='AUTO\\u2192'+aa+' (fleet)';dl.className='chip blue';}"
  "else if(src=='auto-primary'&&aa){dl.textContent='AUTO\\u2192'+aa+' (primary)';dl.className='chip blue';}"
  "else{dl.textContent='AUTO';dl.className='chip idle';}"
  "const mc=document.getElementById('mlchip');"
  "mc.textContent=MLN[j.ml_state]||('state '+j.ml_state);"
  "mc.className='chip '+(j.ml_state===4?'idle':(j.ml_state===6?'red':'warn'));"
  "document.getElementById('hdrml').textContent='tailnet: '+(MLN[j.ml_state]||j.ml_state);"
  "document.getElementById('hdrfw').textContent=j.fw_ver||'';}"
  "async function poll(){"
  "try{"
  "const r=await fetch('/state.json',{cache:'no-store'});"
  "const j=await r.json();"
  "renderHero(j);"
  "renderPeers(j);"
#ifdef DCS_PAGE_MACHINE
  "renderRelays(j);renderOps(j);"
#else
  "renderBtn(j);renderPeerMgmt(j);"
#endif
  "document.getElementById('t0').textContent=j.t0;"
  "document.getElementById('t1').textContent=j.t1;"
  "document.getElementById('l0').textContent=j.l0;"
  "document.getElementById('l1').textContent=j.l1;"
  "document.getElementById('load0').textContent=j.load0+'%';"
  "document.getElementById('load1').textContent=j.load1+'%';"
  "document.getElementById('delta').textContent=j.t0-j.t1;"
  "const ok=j.l0===j.l1;"
  "const a=document.getElementById('agree');"
  "a.textContent=ok?'OK':'MISMATCH';"
  "a.className=ok?'ok':'bad';"
  "lastLoad0=j.load0;lastLoad1=j.load1;"
  "renderBd(document.getElementById('tk0'),j.tk0,j.oth0);"
  "renderBd(document.getElementById('tk1'),j.tk1,j.oth1);"
  "renderBd(document.getElementById('tks'),j.tks,j.oths);"
  "const ds=document.getElementById('dst');"
  "ds.textContent=j.derp_paused?'PAUSED':'running';"
  "ds.className=j.derp_paused?'bad':'ok';"
  "const ws=document.getElementById('wgst');"
  "ws.textContent=j.wg_paused?'PAUSED':'running';"
  "ws.className=j.wg_paused?'bad':'ok';"
  "const us=document.getElementById('usbst');"
  "us.textContent=j.usb_enabled?'ENABLED':'DISABLED';"
  "us.className=j.usb_enabled?'ok':'bad';"
  "const IFN={0:'none',1:'ETHERNET',2:'USB-NCM',3:'WIFI',4:'SoftAP'};"
  "document.getElementById('actif').textContent=IFN[j.active_iface]||j.active_iface;"
  "const es=document.getElementById('ethst');"
  "es.textContent=(j.eth_en?'ENABLED':'disabled')+(j.eth_link?', link up':', no link');"
  "es.className=j.eth_en?'ok':'bad';"
  "const wf=document.getElementById('wifist');"
  "wf.textContent=j.wifi_en?'ENABLED':'disabled';"
  "wf.className=j.wifi_en?'ok':'bad';"
  "const nc=document.getElementById('ncmst');"
  "nc.textContent=j.usbncm_en?'ENABLED':'disabled';"
  "nc.className=j.usbncm_en?'ok':'bad';"
  "if(j.pstop_num!==undefined){"
  "document.getElementById('psncur').textContent=(j.pstop_num===0?'auto':j.pstop_num);"
  "const psi=document.getElementById('psn');"
  "if(!psi.dataset.dirty)psi.value=j.pstop_num;}"
  "document.getElementById('dmsv').textContent=j.derp_delay_ms;"
  "const sl=document.getElementById('dms');"
  "if(!sl.dataset.dirty)sl.value=j.derp_delay_ms;"
  "document.getElementById('txqv').textContent=j.tx_q;"
  "document.getElementById('txdbm').textContent=(j.tx_q/4).toFixed(2);"
  "const tx=document.getElementById('txq');"
  "if(!tx.dataset.dirty)tx.value=j.tx_q;"
  "if(j.led_brightness!==undefined){"
  "document.getElementById('lbrv').textContent=j.led_brightness;"
  "const lbr=document.getElementById('lbr');"
  "if(!lbr.dataset.dirty)lbr.value=j.led_brightness;}"
  "document.getElementById('rssi').textContent=j.rssi;"
  "document.getElementById('heap').textContent=Math.round(j.free_heap/1024);"
  "document.getElementById('lh').textContent=Math.round(j.largest/1024);"
  "document.getElementById('hmi').textContent=Math.round(j.heap_min_int/1024);"
  "document.getElementById('pbf').textContent=j.wg_pbuf_fails;"
  "document.getElementById('bc').textContent=j.boot_count;"
  "const "
  "rrNames={0:'UNKNOWN',1:'POWERON',2:'EXT_PIN',3:'SW',4:'PANIC',5:'INT_WDT',6:'TASK_WDT',7:'WDT',8:'DEEPSLEEP',9:'"
  "BROWNOUT',10:'SDIO',11:'USB',12:'JTAG'};"
  "document.getElementById('rr').textContent=(rrNames[j.reset_reason]||j.reset_reason)+' ('+j.reset_reason+')';"
  "document.getElementById('vm').textContent='VALID (boot ok)';"
  "}catch(e){}"
  "}"
  "document.getElementById('vpncopy').addEventListener('click',()=>{"
  "const t=document.getElementById('vpnip').textContent;"
  "if(!t||t.indexOf('.')<0)return;"
  "const b=document.getElementById('vpncopy');"
  "const done=()=>{b.textContent='copied';setTimeout(()=>b.textContent='copy',1200);};"
  "if(navigator.clipboard){navigator.clipboard.writeText(t).then(done,done);}else{done();}"
  "});"
#ifdef DCS_PAGE_MACHINE
  "document.getElementById('opadd').addEventListener('click',opAdd);"
  "document.getElementById('opid').addEventListener('keydown',e=>{if(e.key==='Enter')opAdd();});"
#else
  "document.getElementById('pmadd').addEventListener('click',pmAdd);"
  "document.getElementById('pmip').addEventListener('keydown',e=>{if(e.key==='Enter')pmAdd();});"
#endif
  "document.getElementById('dbtn').addEventListener('click',async()=>{"
  "try{await fetch('/api/derp',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('usbbtn').addEventListener('click',async()=>{"
  "if(!confirm('Toggle USB tether and reboot?'))return;"
  "try{await fetch('/api/usb_enable',{method:'POST'});}catch(e){}"
  "});"
  "document.getElementById('ethbtn').addEventListener('click',async()=>{"
  "try{await fetch('/api/iface/eth',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('wifibtn').addEventListener('click',async()=>{"
  "try{await fetch('/api/iface/wifi',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('ncmbtn').addEventListener('click',async()=>{"
  "if(!confirm('Toggle USB-NCM? Enabling re-enumerates USB (lose JTAG/flash until reboot).'))return;"
  "try{await fetch('/api/iface/usb',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('psn').addEventListener('input',function(){this.dataset.dirty=1;});"
  "document.getElementById('psnbtn').addEventListener('click',async()=>{"
  "const ps=document.getElementById('psn');"
  "try{await fetch('/api/pstop_num?n='+(ps.value||0),{method:'POST'});}"
  "catch(e){}"
  "finally{delete ps.dataset.dirty;poll();}"
  "});"
  "const sl=document.getElementById('dms');"
  "sl.addEventListener('input',()=>{"
  "sl.dataset.dirty=1;"
  "document.getElementById('dmsv').textContent=sl.value;"
  "});"
  "sl.addEventListener('change',async()=>{"
  "try{await fetch('/api/derp_delay?ms='+sl.value,{method:'POST'});}"
  "catch(e){}"
  "finally{delete sl.dataset.dirty;poll();}"
  "});"
  "const tx=document.getElementById('txq');"
  "tx.addEventListener('input',()=>{"
  "tx.dataset.dirty=1;"
  "document.getElementById('txqv').textContent=tx.value;"
  "document.getElementById('txdbm').textContent=(tx.value/4).toFixed(2);"
  "});"
  "tx.addEventListener('change',async()=>{"
  "try{await fetch('/api/wifi_tx_power?q='+tx.value,{method:'POST'});}"
  "catch(e){}"
  "finally{delete tx.dataset.dirty;poll();}"
  "});"
  "const lbr=document.getElementById('lbr');"
  "lbr.addEventListener('input',()=>{"
  "lbr.dataset.dirty=1;"
  "document.getElementById('lbrv').textContent=lbr.value;"
  "});"
  "lbr.addEventListener('change',async()=>{"
  "try{await fetch('/api/led_brightness?pct='+lbr.value,{method:'POST'});}"
  "catch(e){}"
  "finally{delete lbr.dataset.dirty;poll();}"
  "});"
  "function tickGraph(){"
  "h0.shift();h0.push(lastLoad0);"
  "h1.shift();h1.push(lastLoad1);"
  "draw(c0,h0,'#58a6ff');draw(c1,h1,'#3fb950');"
  "}"
  "setInterval(poll,250);"
  "setInterval(tickGraph,1000);"
  "poll();tickGraph();"
  "</script></body></html>";
