// SPDX-FileCopyrightText: 2026 Polymath Robotics
// SPDX-License-Identifier: Apache-2.0

/**
 * @file dcs_admin_html.h
 * @brief Static HTML for the / index page. Values come from /state.json,
 * so no per-request templating. Kept verbatim from the pre-refactor main.c.
 */

#pragma once

/* Role branding — the same page serves both device roles. The remote is
 * the default; the machn project overrides both macros from its CMake
 * (target_compile_definitions on dcs_support). Icon = a percent-encoded
 * emoji inside an inline SVG data URI (no external assets; the admin
 * server ships no favicon file). */
#ifndef DCS_PAGE_TITLE
  #define DCS_PAGE_TITLE "PSTOP Remote"
#endif
#ifndef DCS_PAGE_ICON
  #define DCS_PAGE_ICON "%F0%9F%9B%91" /* stop sign, percent-encoded for the data URI */
#endif
#ifndef DCS_PAGE_EMOJI
  #define DCS_PAGE_EMOJI "\xF0\x9F\x9B\x91" /* the same glyph, literal UTF-8, for the heading */
#endif

static const char k_index_html[] =
  "<!DOCTYPE html><html><head>"
  "<meta charset='utf-8'>"
  "<meta name='viewport' content='width=device-width,initial-scale=1'>"
  "<title>" DCS_PAGE_TITLE "</title>"
  "<link rel='icon' href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>"
  "<text y='.9em' font-size='90'>" DCS_PAGE_ICON "</text></svg>\">"
  "<style>body{font-family:system-ui;background:#0d1117;color:#e6edf3;"
  "display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0}"
  ".card{background:#161b22;border:1px solid #30363d;border-radius:12px;"
  "padding:32px;min-width:420px}"
  "h1{color:#58a6ff;margin:0 0 16px}"
  "table{width:100%;border-collapse:collapse;font-family:monospace}"
  "th,td{padding:6px 10px;text-align:left;border-bottom:1px solid #30363d;"
  "vertical-align:top}"
  "th{color:#8b949e;font-weight:normal}"
  ".ok{color:#3fb950}.bad{color:#f85149}"
  "canvas{background:#0d1117;border:1px solid #30363d;display:block}"
  ".bd{font-size:.85em;line-height:1.5;min-height:6.4em}"
  ".bd .row{display:flex;justify-content:space-between;gap:8px}"
  ".bd .row.dim{color:#6e7681}"
  "p{color:#8b949e}a{color:#58a6ff}</style></head><body>"
  "<div class='card'><h1>" DCS_PAGE_EMOJI " " DCS_PAGE_TITLE "</h1>"
  "<table>"
  "<tr><th></th><th>Core 0 (D0)</th><th>Core 1 (D1)</th></tr>"
  "<tr><th>ticks</th><td id='t0'>-</td><td id='t1'>-</td></tr>"
  "<tr><th>level</th><td id='l0'>-</td><td id='l1'>-</td></tr>"
  "<tr><th>load</th><td id='load0'>-</td><td id='load1'>-</td></tr>"
  "<tr><th>30s</th>"
  "<td><canvas id='g0' width='180' height='40'></canvas></td>"
  "<td><canvas id='g1' width='180' height='40'></canvas></td></tr>"
  "<tr><th>tasks</th>"
  "<td><div id='tk0' class='bd'>-</div></td>"
  "<td><div id='tk1' class='bd'>-</div></td></tr>"
  "<tr><th>shared</th>"
  "<td colspan='2'><div id='tks' class='bd'>-</div></td></tr>"
  "</table>"
  "<p>tick delta: <span id='delta'>-</span>"
  " &nbsp;|&nbsp; agreement: <span id='agree'>-</span></p>"
  "<p>DERP TX task: <span id='dst'>-</span>"
  " &nbsp;<button id='dbtn' type='button'>toggle</button></p>"
  "<p>WG manager (DISCO probes): <span id='wgst'>-</span>"
  " &nbsp;<button id='wgbtn' type='button'>toggle</button></p>"
  "<p>USB tether: <span id='usbst'>-</span>"
  " &nbsp;<button id='usbbtn' type='button'>toggle (reboots)</button></p>"
  "<p style='margin-top:1em'><b>Network interfaces</b> &nbsp; active: <span id='actif' class='ok'>-</span></p>"
  "<p>Ethernet (W5500): <span id='ethst'>-</span>"
  " &nbsp;<button id='ethbtn' type='button'>toggle</button></p>"
  "<p>WiFi STA: <span id='wifist'>-</span>"
  " &nbsp;<button id='wifibtn' type='button'>toggle</button></p>"
  "<p>USB Ethernet (NCM): <span id='ncmst'>-</span>"
  " &nbsp;<button id='ncmbtn' type='button'>toggle (USB re-enum)</button></p>"
  "<p>USB unit (PSTOPxx): <input id='psn' type='number' min='0' max='99' style='width:4em'>"
  " <button id='psnbtn' type='button'>set</button> cfg=<span id='psncur'>-</span>"
  " &nbsp;<small>(0=auto from chip ID; reboot to apply)</small></p>"
  "<p>DERP yield: <input id='dms' type='range' min='1' max='100' value='1'"
  " style='vertical-align:middle'> <span id='dmsv'>-</span> ms</p>"
  "<p>WiFi TX power: <input id='txq' type='range' min='8' max='84' value='52'"
  " style='vertical-align:middle'> <span id='txqv'>-</span>"
  " &nbsp;(<span id='txdbm'>-</span> dBm)</p>"
  "<p>RSSI: <span id='rssi'>-</span> dBm"
  " &nbsp;|&nbsp; free heap: <span id='heap'>-</span> KiB"
  " &nbsp;|&nbsp; largest: <span id='lh'>-</span> KiB"
  " &nbsp;|&nbsp; min internal: <span id='hmi'>-</span> KiB"
  " &nbsp;|&nbsp; wg pbuf fails: <span id='pbf'>-</span></p>"
  "<p>SAFETY: boot # <span id='bc'>-</span> &nbsp;|&nbsp;"
  " reset reason: <span id='rr'>-</span> &nbsp;|&nbsp;"
  " valid-mark: <span id='vm'>-</span></p>"
#ifdef DCS_PAGE_MACHINE
  "<p style='margin-top:1em'><b>Stop-circuit relays</b> <small>(series chain: either opens = STOP)</small></p>"
  "<div id='relays' class='bd'>-</div>"
  "<p id='rstop' class='bad' style='display:none;font-weight:bold'>&#9888; RELAY FAULT &mdash; robot stop forced "
  "until feedback recovers</p>"
#else
  "<p style='margin-top:1em'><b>STOP button</b> <small>(dual-channel DPST, live &mdash; no peer needed)</small></p>"
  "<div id='btnstat' style='font-size:1.4em;font-weight:bold;margin:6px 0'>-</div>"
  "<div id='btn' class='bd'>-</div>"
  "<p><button id='ringtestbtn' type='button'>ring test (all white, 5 min)</button>"
  " <button id='ringtestoff' type='button'>off</button></p>"
#endif
  "<p style='margin-top:1em'><b>PSTOP peers</b> <small>(bonded devices, live)</small></p>"
  "<div id='peers' class='bd'>-</div>"
  "<p><a href='/admin/'>Admin Panel</a></p>"
  "</div>"
  "<script>"
  "const N=30;"
  "const h0=new Array(N).fill(0),h1=new Array(N).fill(0);"
  "const c0=document.getElementById('g0'),c1=document.getElementById('g1');"
  "let lastLoad0=0,lastLoad1=0;"
  "function draw(c,h,col){"
  "const x=c.getContext('2d'),W=c.width,H=c.height;"
  "x.fillStyle='#0d1117';x.fillRect(0,0,W,H);"
  "x.strokeStyle='#21262d';x.lineWidth=1;"
  "for(const p of[25,50,75]){"
  "const y=Math.round(H-(p/100)*H)+0.5;"
  "x.beginPath();x.moveTo(0,y);x.lineTo(W,y);x.stroke();}"
  "x.strokeStyle=col;x.lineWidth=1.5;x.beginPath();"
  "for(let i=0;i<N;i++){"
  "const px=(i/(N-1))*W,py=H-(h[i]/100)*H;"
  "if(i===0)x.moveTo(px,py);else x.lineTo(px,py);}"
  "x.stroke();}"
  "function renderBd(el,arr,other){"
  "if(!arr){el.textContent='-';return;}"
  "let html='';"
  "for(const[n,p]of arr){"
  "html+='<div class=\"row\"><span>'+n+'</span><span>'+p+'%</span></div>';}"
  "if(other>0){"
  "html+='<div class=\"row dim\"><span>(other)</span><span>'+other+'%</span></div>';}"
  "el.innerHTML=html||'-';}"
#ifdef DCS_PAGE_MACHINE
  "function relayRow(name,cmd,obs,fault){"
  "const match=(fault||0)===0;"
  "const cls=match?(cmd?'ok':''):'bad';"
  "let st=match?(cmd?'RUN':'open'):('FAULT \u00d7'+fault);"
  "return '<div class=\"row\"><span>relay '+name+' &nbsp; coil: '+(cmd?'energized':'released')"
  "+' &nbsp;&middot;&nbsp; feedback: '+(obs?'live':'dead')+'</span>'"
  "+'<span class=\"'+cls+'\">'+st+'</span></div>';}"
  "function renderRelays(j){"
  "const el=document.getElementById('relays');if(!el)return;"
  "el.innerHTML=relayRow('A',j.e_hi0,j.e_lo0,j.relay_fault_a)+relayRow('B',j.e_hi1,j.e_lo1,j.relay_fault_b);"
  "document.getElementById('rstop').style.display=j.relay_stop?'block':'none';}"
#else
  /* Remote STOP-button panel: e_hi = drive-high reads high (loop closed),
   * e_lo = drive-low reads low (pull-down intact). Loop OPEN (e_hi=0) = pressed;
   * e_lo=0 = a wiring fault (can't pull the sense line low). No peer needed. */
  "function btnRow(name,hi,lo){"
  "let st,cls;"
  "if(!lo){st='WIRING FAULT';cls='bad';}"
  "else if(hi){st='closed';cls='ok';}"
  "else{st='OPEN (pressed)';cls='';}"
  "return '<div class=\"row\"><span>channel '+name+' &nbsp; drive-hi: '+(hi?'ok':'low')"
  "+' &middot; drive-lo: '+(lo?'ok':'HIGH')+'</span><span class=\"'+cls+'\">'+st+'</span></div>';}"
  "function renderBtn(j){"
  "const el=document.getElementById('btn');if(!el)return;"
  "el.innerHTML=btnRow('A',j.e_hi0,j.e_lo0)+btnRow('B',j.e_hi1,j.e_lo1);"
  "const pressed=(!j.e_hi0)&&(!j.e_hi1),wok=j.e_lo0&&j.e_lo1;"
  "const s=document.getElementById('btnstat');"
  "if(!wok){s.textContent='⚠ WIRING FAULT';s.className='bad';}"
  "else if(pressed){s.textContent='● PRESSED (STOP)';s.className='bad';}"
  "else{s.textContent='○ RELEASED (run)';s.className='ok';}}"
#endif
  "const MS=['idle','bonding','bonded'];"
  "const RS=['initing','bonded','OK','STOP'];"
  "function ip4(v){return[(v>>>24)&255,(v>>>16)&255,(v>>>8)&255,v&255].join('.');}"
  "function lnk(ip){return '<a href=\"http://'+ip+'/\" target=\"_blank\" rel=\"noopener\">'+ip+'</a>';}"
  "function pathrtt(o){if(!o.wg_rtt_ms||o.wg_rtt_age_ms>60000)return'';"
  "return ' \u00b7 path '+o.wg_rtt_ms+' ms '+(o.wg_direct?'(direct)':'(relay)');}"
  "function renderPeers(j){"
  "const el=document.getElementById('peers');if(!el)return;"
  "let h='';"
#ifdef DCS_PAGE_MACHINE
  "for(const m of []){" /* a MACHINE has no machine peers — the dcs slot table
                          * is a remote-role vestige; never render it here */
#else
  "for(const m of(j.pstop_machines||[])){"
#endif
  "if(!m.cfg)continue;"
  "const age=j.uptime_ms&&m.last_reply_ms?Math.max(0,j.uptime_ms-m.last_reply_ms):null;"
  "const live=m.state==2&&age!=null&&age<3000;"
  "h+='<div class=\"row'+(live?'':' dim')+'\"><span>machine 0x'+(m.id>>>0).toString(16)+' @ '+lnk(ip4(m.ip))+':'+m.port+' "
  "['+(MS[m.state]||m.state)+']</span>'"
  "+'<span>loop '+m.rtt_ms+' ms'+pathrtt(m)+(age!=null?' \u00b7 heard '+(age/1000).toFixed(1)+'s ago':'')+'</span></div>';}"
  "for(const q of(j.bonded_remotes||[])){"
  "const live=q.age_ms<3000;"
  "h+='<div class=\"row'+(live?'':' dim')+'\"><span>remote 0x'+(q.id>>>0).toString(16)+' @ '+lnk(ip4(q.ip))+' "
  "['+(RS[q.state]||q.state)+']</span>'"
  "+'<span>loop\u2264 '+q.rtt_ms+' ms'+pathrtt(q)+' \u00b7 heard '+(q.age_ms/1000).toFixed(1)+'s ago</span></div>';}"
  "el.innerHTML=h||'<div class=\"row dim\"><span>none</span><span></span></div>';}"
  "async function poll(){"
  "try{"
  "const r=await fetch('/state.json',{cache:'no-store'});"
  "const j=await r.json();"
  "renderPeers(j);"
#ifdef DCS_PAGE_MACHINE
  "renderRelays(j);"
#else
  "renderBtn(j);"
#endif
  "document.getElementById('t0').textContent=j.t0;"
  "document.getElementById('t1').textContent=j.t1;"
  "document.getElementById('l0').textContent=j.l0;"
  "document.getElementById('l1').textContent=j.l1;"
  "document.getElementById('load0').textContent=j.load0+'%';"
  "document.getElementById('load1').textContent=j.load1+'%';"
  "document.getElementById('delta').textContent=j.t0-j.t1;"
  "const ok=j.l0===j.l1;"
  "const a=document.getElementById('agree');"
  "a.textContent=ok?'OK':'MISMATCH';"
  "a.className=ok?'ok':'bad';"
  "lastLoad0=j.load0;lastLoad1=j.load1;"
  "renderBd(document.getElementById('tk0'),j.tk0,j.oth0);"
  "renderBd(document.getElementById('tk1'),j.tk1,j.oth1);"
  "renderBd(document.getElementById('tks'),j.tks,j.oths);"
  "const ds=document.getElementById('dst');"
  "ds.textContent=j.derp_paused?'PAUSED':'running';"
  "ds.className=j.derp_paused?'bad':'ok';"
  "const ws=document.getElementById('wgst');"
  "ws.textContent=j.wg_paused?'PAUSED':'running';"
  "ws.className=j.wg_paused?'bad':'ok';"
  "const us=document.getElementById('usbst');"
  "us.textContent=j.usb_enabled?'ENABLED':'DISABLED';"
  "us.className=j.usb_enabled?'ok':'bad';"
  "const IFN={0:'none',1:'ETHERNET',2:'USB-NCM',3:'WIFI',4:'SoftAP'};"
  "document.getElementById('actif').textContent=IFN[j.active_iface]||j.active_iface;"
  "const es=document.getElementById('ethst');"
  "es.textContent=(j.eth_en?'ENABLED':'disabled')+(j.eth_link?', link up':', no link');"
  "es.className=j.eth_en?'ok':'bad';"
  "const wf=document.getElementById('wifist');"
  "wf.textContent=j.wifi_en?'ENABLED':'disabled';"
  "wf.className=j.wifi_en?'ok':'bad';"
  "const nc=document.getElementById('ncmst');"
  "nc.textContent=j.usbncm_en?'ENABLED':'disabled';"
  "nc.className=j.usbncm_en?'ok':'bad';"
  "if(j.pstop_num!==undefined){"
  "document.getElementById('psncur').textContent=(j.pstop_num===0?'auto':j.pstop_num);"
  "const psi=document.getElementById('psn');"
  "if(!psi.dataset.dirty)psi.value=j.pstop_num;}"
  "document.getElementById('dmsv').textContent=j.derp_delay_ms;"
  "const sl=document.getElementById('dms');"
  "if(!sl.dataset.dirty)sl.value=j.derp_delay_ms;"
  "document.getElementById('txqv').textContent=j.tx_q;"
  "document.getElementById('txdbm').textContent=(j.tx_q/4).toFixed(2);"
  "const tx=document.getElementById('txq');"
  "if(!tx.dataset.dirty)tx.value=j.tx_q;"
  "document.getElementById('rssi').textContent=j.rssi;"
  "document.getElementById('heap').textContent=Math.round(j.free_heap/1024);"
  "document.getElementById('lh').textContent=Math.round(j.largest/1024);"
  "document.getElementById('hmi').textContent=Math.round(j.heap_min_int/1024);"
  "document.getElementById('pbf').textContent=j.wg_pbuf_fails;"
  "document.getElementById('bc').textContent=j.boot_count;"
  "const "
  "rrNames={0:'UNKNOWN',1:'POWERON',2:'EXT_PIN',3:'SW',4:'PANIC',5:'INT_WDT',6:'TASK_WDT',7:'WDT',8:'DEEPSLEEP',9:'"
  "BROWNOUT',10:'SDIO',11:'USB',12:'JTAG'};"
  "document.getElementById('rr').textContent=(rrNames[j.reset_reason]||j.reset_reason)+' ('+j.reset_reason+')';"
  "document.getElementById('vm').textContent='VALID (boot ok)';"
  "}catch(e){}"
  "}"
  "document.getElementById('dbtn').addEventListener('click',async()=>{"
  "try{await fetch('/api/derp',{method:'POST'});poll();}catch(e){}"
  "});"
  "const rtb=document.getElementById('ringtestbtn');"
  "if(rtb)rtb.addEventListener('click',async()=>{"
  "try{await fetch('/api/ring_test?on=1',{method:'POST'});}catch(e){}});"
  "const rto=document.getElementById('ringtestoff');"
  "if(rto)rto.addEventListener('click',async()=>{"
  "try{await fetch('/api/ring_test?on=0',{method:'POST'});}catch(e){}});"
  "document.getElementById('wgbtn').addEventListener('click',async()=>{"
  "try{await fetch('/api/wg',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('usbbtn').addEventListener('click',async()=>{"
  "if(!confirm('Toggle USB tether and reboot?'))return;"
  "try{await fetch('/api/usb_enable',{method:'POST'});}catch(e){}"
  "});"
  "document.getElementById('ethbtn').addEventListener('click',async()=>{"
  "try{await fetch('/api/iface/eth',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('wifibtn').addEventListener('click',async()=>{"
  "try{await fetch('/api/iface/wifi',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('ncmbtn').addEventListener('click',async()=>{"
  "if(!confirm('Toggle USB-NCM? Enabling re-enumerates USB (lose JTAG/flash until reboot).'))return;"
  "try{await fetch('/api/iface/usb',{method:'POST'});poll();}catch(e){}"
  "});"
  "document.getElementById('psn').addEventListener('input',function(){this.dataset.dirty=1;});"
  "document.getElementById('psnbtn').addEventListener('click',async()=>{"
  "const ps=document.getElementById('psn');"
  "try{await fetch('/api/pstop_num?n='+(ps.value||0),{method:'POST'});}"
  "catch(e){}"
  "finally{delete ps.dataset.dirty;poll();}"
  "});"
  "const sl=document.getElementById('dms');"
  "sl.addEventListener('input',()=>{"
  "sl.dataset.dirty=1;"
  "document.getElementById('dmsv').textContent=sl.value;"
  "});"
  "sl.addEventListener('change',async()=>{"
  "try{await fetch('/api/derp_delay?ms='+sl.value,{method:'POST'});}"
  "catch(e){}"
  "finally{delete sl.dataset.dirty;poll();}"
  "});"
  "const tx=document.getElementById('txq');"
  "tx.addEventListener('input',()=>{"
  "tx.dataset.dirty=1;"
  "document.getElementById('txqv').textContent=tx.value;"
  "document.getElementById('txdbm').textContent=(tx.value/4).toFixed(2);"
  "});"
  "tx.addEventListener('change',async()=>{"
  "try{await fetch('/api/wifi_tx_power?q='+tx.value,{method:'POST'});}"
  "catch(e){}"
  "finally{delete tx.dataset.dirty;poll();}"
  "});"
  "function tickGraph(){"
  "h0.shift();h0.push(lastLoad0);"
  "h1.shift();h1.push(lastLoad1);"
  "draw(c0,h0,'#58a6ff');draw(c1,h1,'#3fb950');"
  "}"
  "setInterval(poll,250);"
  "setInterval(tickGraph,1000);"
  "poll();tickGraph();"
  "</script></body></html>";
