// SPDX-FileCopyrightText: 2026 Polymath Robotics
// SPDX-License-Identifier: Apache-2.0

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per top-level docs directory; each is a navbar tab.
const sidebars: SidebarsConfig = {
  guides: [{type: 'autogenerated', dirName: 'guides'}],
  hardware: [{type: 'autogenerated', dirName: 'hardware'}],
  safety: [{type: 'autogenerated', dirName: 'safety'}],
  design: [{type: 'autogenerated', dirName: 'design'}],
  developing: [{type: 'autogenerated', dirName: 'developing'}],
  archive: [{type: 'autogenerated', dirName: 'archive'}],
};

export default sidebars;
